site_name: numa-sea Documents
repo_url: https://github.com/numa-sea/numadocs
copyright: Copyright &copy; numa-sea

theme:
  name: material
  palette:
    - scheme: slate
      primary: blue
      accent: blue
      
  features:
    - navigation.top
    - content.code.annotate

plugins:
  - search
  - git-revision-data-localized

markdown_extensions:
  - codehilite
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.highlight:
      auto_title: true
      pygments_lang_class: true
      anchor_linenums: true

nav:
-TOP: index.md

