site_name: numa-sea Documents
repo_url: https://github.com/numa-sea/numadocs
copyright: Copyright &copy; numa-sea

markdown_extensions:
  - codehilite
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.highlight:
      auto_title: true
      pygments_lang_class: true
      anchor_linenums: true

nav:
- index.md