site_name: numa-sea Documents
repo_url: https://github.com/numa-sea/numadocs

theme:
  name: material
  palette:
    - scheme: slate
      primary: blue
      accent: blue
      toggle:
          icon: material/toggle-switch
          name: disable dark mode
    - scheme: default
      toggle:
          icon: material/toggle-switch-off-outline
          name: enable dark mode
    
  features:
    - navigation.top
    - content.code.annotate

# plugins:
#   - search
#   - git-revision-date-localized

markdown_extensions:
  - codehilite
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.highlight:
      auto_title: true
      pygments_lang_class: true
      anchor_linenums: true

# nav:
# - TOP
# - Arduino
#   - 1. 環境構築
#   - 2. Lチカ
#   - 3. UART通信(serial)